---
images:
  gitInit: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:9b14f52b21d29d8d83ea4c0e78623debc954f1a732d2be6d1a7269fbba23b1a4

annotations:
  tekton.dev/pipelines.minVersion: "0.38.0"
  tekton.dev/categories: Git
  tekton.dev/tags: git
  tekton.dev/displayName: "git"
  tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"

stepTemplate:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65532
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
